setwd("C:/Users/chint/Documents/R codes")
data <- read.csv("Yearlife.csv")  
print(data)
Year <- c(data$YearofBirth)  
Life<- c(data$LifeExpectancy)
relationship_model<- lm(Life~Year)  
png(file = "linear_regression_LifevsYear.png")  
plot(Life,Year,col = "blue",main = "Year vs Life",abline(lm(Year~Life)),cex = 1.3,pch = 16,xlab = "Life",ylab = "year")  
dev.off()
print(relationship_model)
print(summary(relationship_model))
z <- data.frame(Year = 1972)  
predict_result<-  predict(relationship_model,z)  
print(predict_result)

png(file = "scatterplot.png")
plot(x = Life,y = Year, xlab = "Life", ylab = "year", xlim = c(55,80), ylim = c(1925,2015), main = "Year vs Life")  
dev.off()
print(cor(Year,Life))
print(cor.test(Life,Year))